### ISSUE TITLE
Publish latest package on npmjs.org

### ISSUE THREAD

**Issue by williamsbdev** [PagerDuty/pdjs#104]
Thanks for this project! I would love to have an easy way to consume the latest code from this package from npmjs.org.

It looks like this package was last published nearly 2 years ago (see issue #18). Would it be possible to have [CircleCI](https://github.com/PagerDuty/pdjs/blob/main/.circleci/config.yml) publish the latest version of this package upon each new tag created?

**Comment by williamsbdev** [comment]
My apologies. The latest version is published:

https://www.npmjs.com/package/@pagerduty/pdjs

I'm curious if this [one](https://www.npmjs.com/package/pagerduty-pdjs) is for the v1 API? If it's not and it's been superseded by the one above, I would suggest putting up a deprecation warning and pointing to the new package and/or deleting.

**Comment by bzmw** [comment]
Thanks for the notice @williamsbdev , I've gone and deprecated the old package!
