### ISSUE TITLE
delete response with response lacking response body throws exception

### ISSUE THREAD

**Issue by csumpter** [PagerDuty/pdjs#142]
Hi Pagerduty,

When you make a `DELETE` call to `/services/<service-id>` the default response will be a `204` without a response body and the code will try to process the response through a `.json()` call on https://github.com/PagerDuty/pdjs/blob/main/src/api.ts#L100 and throw hitting the `.catch` even on a valid response, thereby rejecting the promise.

library version: `2.2.1`

Please let me know if I can provide additional context.

**Comment by bzmw** [comment]
Hey @csumpter , thanks for the report we'll have a look into this in the next few weeks. If you have time to attempt a fix yourself that would be super helpful.
Thanks!
