### ISSUE TITLE
Cannot fetch list of change events

### ISSUE THREAD

**Issue by gabrielso** [PagerDuty/pdjs#146]
I can fetch (GET) the list of changes from the `/change_events` endpoint with Postman, but not from the browser. Seems like the CORS header is not set for this endpoint. Is this an issue with this library or with the API?

Sample:
```javascript
const pd = api({ token: "<token>" })

pd.get("/change_events")
  .then(({ data }) => console.log(data))
```

Result in the browser console:
```
Access to XMLHttpRequest at 'https://api.pagerduty.com/change_events' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I get a correct response when fetching the `/incidents` endpoint, for instance, so the library is properly set up in my project.

The README of this repository mentions support to the Events API v2 but I couldn't find a way to list change events as shown in the [documentation](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1change_events/get).

**Comment by bzmw** [comment]
Hey there! Thanks for reporting this we're taking a look!

**Comment by gabrielso** [comment]
Hello @bzmw, hope you're having a great week!
Any update on the CORS configuration for the `/change_events` endpoint?

**Comment by bzmw** [comment]
Hey @gabrielso , we have identified the problem and have prioritized a fix. The problem is with the endpoint not with this library however.

**Comment by gabrielso** [comment]
@bzmw thanks for the update. I'd appreciate if someone could give me a heads-up when the issue is fixed. I'll close the ticket since it's not pertinent to this project.

Cheers!

**Comment by ChezCrawford** [comment]
@gabrielso : This issue should be resolved now.  Have a look and let us know if you run into additional issues.

**Comment by gabrielso** [comment]
Works for me™
