### ISSUE TITLE
Why isn't this on npm?

### ISSUE THREAD

**Issue by krstffr** [PagerDuty/pdjs#18]
Would be awesome to be able to `npm install` this!

**Comment by ParthKolekar** [comment]
Bump. Yes that would be awesome.

**Comment by tarekrached** [comment]
forreals

**Comment by stmcallister** [comment]
Hi All! Thanks for requesting this feature! Just a quick question, so we can best provide a tool that would be useful to you. 

Would you be wanting to use `pdjs` npm package in node or in the browser? Currently, the library is built off of the `window` object, thus making it only compatible as a client-side library. 

If you're looking for a good node library, I would recommend: https://github.com/kmart2234/node-pagerduty

Would love to know your use cases. Please list them in the comments so we can best understand what everyone is looking for.

**Comment by tarekrached** [comment]
Yeah, https://github.com/kmart2234/node-pagerduty is what we landed on for server-side duty.  I'd love to be able to include this in a create react app application, and npm installing it would make that super easy.

**Comment by stmcallister** [comment]
Thanks for responding @tarekrached! I have a test npm package created, and I'm in the process of testing it. While I do that, I'm curious. What use cases would you want to use a client-side JS library as apposed to a server side? Where do you store your access token?

I'm relatively new to PagerDuty, so I'm just trying to get an idea of what people are using the different libraries for.

I'll keep you posted on my npm package testing.

**Comment by stmcallister** [comment]
Give this a shot: https://www.npmjs.com/package/pagerduty-pdjs
