### ISSUE TITLE
Expose typescript interfaces

### ISSUE THREAD

**Issue by Zaimwa9** [PagerDuty/pdjs#184]
Hi, all the interfaces seem to be exported from `src/api.ts`. Would it be possible to directly export them in the sdk entrypoint please.

There is a turnround I know but it would be cleaner and easier to be able to import them directly. I have a branch ready to be pushed.

Let me know if I missed something or if this could be done.

Thanks

**Comment by bzmw** [comment]
Hey @Zaimwa9 , can you push up your branch so I can see how the change looks?

**Comment by bzmw** [comment]
Going to close this as it is stale now.
