### ISSUE TITLE
Appears to leave pending timeouts after request completes successfully

### ISSUE THREAD

**Issue by davidmc24** [PagerDuty/pdjs#202]
Thank you for this library.  Overall, it was easy to use and did what it needed to.  I just ran into one small problem with it.

I'm working on a Node process that creates PagerDuty Events with this library.  I'm currently testing some of the logic with a simple command-line script that creates the event and then completes.

My expectation was that the process would exit immediately after returning, but what I'm actually seeing is that, by default, the process doesn't exit until 30 seconds later.  Through experimentation, I determined that configuring `requestTimeout` adjusts how long the process hangs after completion.

It seems likely that you're missing some `clearTimeout` calls.

Minimal script to reproduce below.

Run it like this:

* `time node index.mjs <ROUTING_KEY>`
    * Expected to complete shortly after event is created, but currently runs for ~30 seconds
* `time node index.mjs <ROUTING_KEY> 1000`
    * Expected to complete shortly after event is created, but currently runs for ~1 second

```js
import {event} from '@pagerduty/pdjs';
const routing_key = process.argv[2];
const requestTimeout = process.argv[3];
console.info(`Using requestTimeout ${requestTimeout}`);
event({
  data: {
    routing_key,
    event_action: 'trigger',
    dedup_key: 'test_incident_2_88f520',
    payload: {
      summary: 'Test Event V2',
      source: 'test-source',
      severity: 'error',
    },
  },
  requestTimeout
})
  .then((event) => {console.info('Success')})
  .catch((err) => {console.error('Error', err)});
```

**Comment by bzmw** [comment]
Thank you for the very well documented bug report!

We'll get to fixing this in the next few weeks.
