### ISSUE TITLE
Inverted if statement when setting user agent header

### ISSUE THREAD

**Issue by joshmsamuels** [PagerDuty/pdjs#245]
When setting the user agent header in `pdjs/src/common.ts` the `userAgentHeader` function sets the header to an empty object in a browser and otherwise sets the header using node properties (`process`).

To be resilient to other applications (e.g. web workers), this function should set the user agent header using `process` only if the environment is node

**Comment by joshmsamuels** [comment]
@bzmw It looks like you are the owner of pdjs. What are your thoughts on this issue? If you like my proposed solution I am happy to submit a PR

**Comment by bzmw** [comment]
Thanks for the report @joshmsamuels I've got a PR up to fix this, new version coming soon.
