### ISSUE TITLE
I can't pass custom headers in post request

### ISSUE THREAD

**Issue by aabadia** [PagerDuty/pdjs#276]
I need to pass some headers to invoke incidents API but, the current API doesn't allow it. 

Example request:

https://developer.pagerduty.com/api-reference/b3A6Mjc0ODE0MA-create-an-incident
```javascript
import axios from "axios";
const options = {
method: 'POST',
url: 'https://api.pagerduty.com/incidents',
headers: {
'Content-Type': 'application/json',
Accept: 'application/vnd.pagerduty+json;version=2',
From: ***@***.***',
Authorization: 'Token token=REVOKED'
},
data: {
incident: {
type: 'incident',
title: 'The server is on fire.',
service: {id: 'PWIXJZS', type: 'service_reference'},
priority: {id: 'P53ZZH5', type: 'priority_reference'},
urgency: 'high',
incident_key: 'baf7cf21b1da41b4b0221008339ff357',
body: {
type: 'incident_body',
details: 'A disk is getting full on this machine. You should investigate
what is causing the disk to fill, and ensure that there is an automated
process in place for ensuring data is rotated (eg. logs should have
logrotate around them). If data is expected to stay on this disk forever,
you should start planning to scale up to a larger disk.'
},
escalation_policy: {id: 'PT20YPA', type: 'escalation_policy_reference'}
}
}
};
axios.request(options).then(function (response) {
console.log(response.data);
}).catch(function (error) {
console.error(error);
});
```

**Comment by bzmw** [comment]
Can you give an example of what custom headers you would need to pass? What is the use case here?

**Comment by aabadia** [comment]
Yes. To create a new incident:
https://developer.pagerduty.com/api-reference/b3A6Mjc0ODE0MA-create-an-incident


import axios from "axios";
const options = {
method: 'POST',
url: 'https://api.pagerduty.com/incidents',
headers: {
'Content-Type': 'application/json',
Accept: 'application/vnd.pagerduty+json;version=2',
From: ***@***.***',
Authorization: 'Token token=y_NbAkKc66ryYTWUXYEu'
},
data: {
incident: {
type: 'incident',
title: 'The server is on fire.',
service: {id: 'PWIXJZS', type: 'service_reference'},
priority: {id: 'P53ZZH5', type: 'priority_reference'},
urgency: 'high',
incident_key: 'baf7cf21b1da41b4b0221008339ff357',
body: {
type: 'incident_body',
details: 'A disk is getting full on this machine. You should investigate
what is causing the disk to fill, and ensure that there is an automated
process in place for ensuring data is rotated (eg. logs should have
logrotate around them). If data is expected to stay on this disk forever,
you should start planning to scale up to a larger disk.'
},
escalation_policy: {id: 'PT20YPA', type: 'escalation_policy_reference'}
}
}
};
axios.request(options).then(function (response) {
console.log(response.data);
}).catch(function (error) {
console.error(error);
});

**Comment by bzmw** [comment]
@aabadia the example you posted uses `axios` and not this library. 

I do not see an issue with the code you posted thought, what errors are you getting in return?

**Comment by aabadia** [comment]
Using this library, I can set the URI and the payload, but I can't set the
required header called "From".

**Comment by bzmw** [comment]
I just tested this and it worked fine.  Can you try implementing it through my example?

Here is my test code:
```javascript
      const pd = PagerDuty.api({token: 'REVOKED', tokenType: 'token'});
      const openIncidents = pd.post('/incidents',
        {
          headers: {
            'From': '**@**.**'
          },
          data: {
            "incident": {
              "type": "incident",
              "title": "The server is on fire.",
              "service": {
                "id": "REVOKED",
                "type": "service_reference"
              },
              "urgency": "high",
              "body": {
                "type": "incident_body",
                "details": "Some details."
              }
            }
          }
        }
      )
```

**Comment by obochurkin** [comment]
Will rise this again. Seems there is no `headers` option in api.d.ts ```APIParameters.headers?:```
got this: 
```
Argument of type '{ headers: { From: string; }; data: IncidentDataType; }' is not assignable to parameter of type 'Partial<APIParameters>'.
  Object literal may only specify known properties, and 'headers' does not exist in type 'Partial<APIParameters>'.ts(2345)
```

moved to https://github.com/PagerDuty/pdjs/issues/370
